title: Taylor Hess Blog
author: thess24
description: > # this means to ignore newlines until "baseurl:"
  A blog on Machine Learning, Quant Finance, Computer Science, System Design, and more.
# social links
# twitter_username: your-twitter-handle
# github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-cayman
