title: Taylor Hess Blog
author: thess24
permalink: /:title
# baseurl: /
description: > # this means to ignore newlines until "baseurl:"
  A blog on Machine Learning, Quant Finance, Computer Science, System Design, and more.
# social links

# header_pages:
#   - about.md
  
show_excerpts: true # set to false to remove excerpts on the homepage

#theme: jekyll-theme-cayman
theme: jekyll-theme-minima
